version: "2.21"

services:
  frontend:
    build: ./app/frontend
    volumes:
      - ./app/frontend:/frontend
      - /frontend/node_modules
      - /frontend/dist
    ports:
      - 3000:3000
    container_name: frontend
  backend:
    env_file: ./app/backend/.env.develop
    build: ./app/backend
    volumes:
      - ./app/backend:/backend
      - /backend/node_modules
    ports:
      - 8080:8080
      - 9229:9229
    container_name: backend
    depends_on:
      - mysql-db
      #- mongo-db
      #- rabbitmq
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    env_file:
      - .env.db
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      #  mongo-db:
      #    image: mongo:latest
      #    container_name: mongo-db
      #    ports:
      #      - 27017:27017
      #    volumes:
      #      - ./data/mongo/d–∞ta:/data/db
      #    env_file:
      #- .env.db
#  rabbitmq:
#    image: rabbitmq:3.12-alpine
#    container_name: rabbitmq
#    ports:
#      - 5672:5672
#    volumes:
#      - ./rabbitmq/data/:/var/lib/rabbitmq
#      - ./rabbitmq//local/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
